### ISSUE TITLE
Inconsistency with built-in array_column() when 3rd parameter element value is not string

### ISSUE THREAD

**Issue by forcodeprojecthosting** [ramsey/array_column#11]
Your `array_column()` is giving different results from PHP's built-in `array_column()` if the 3<sup>rd</sup> parameter is not `null` and the element value is not a string. For example:

```
$records = array(
    array('id' => 2135, 'first_name' => 'John', 'last_name' => 'Doe'),
    array('id' => true, 'first_name' => 'Sally', 'last_name' => 'Smith'),
    array('id' => null, 'first_name' => 'Jane', 'last_name' => 'Jones'),
    array('id' => 56.23, 'first_name' => 'Peter', 'last_name' => 'Doe'),
);
```

PHP 5.6.3 `array_column()` gives:

```
Array
(
    [2135] => Doe
    [2136] => Smith
    [2137] => Jones
    [2138] => Doe
)
```

Your `array_column()` gives:
```
Array
(
    [2135] => Doe
    [1] => Smith
    [] => Jones
    [56.23] => Doe
)
```

**Comment by ramsey** [comment]
This is a known issue in PHP: https://bugs.php.net/bug.php?id=68553

Take a look at the output you pasted for 5.6.3. The indexes are consecutive `2135`, `2136`, `2137`, and `2138`, even though the `id` field for your `$records` array contains `2135`, `true`, `null`, `56.23`. Even if you use the string value `id` as the 3rd parameter, you get the wrong results:

``` php
array_column($records, 'last_name', 'id');
```

The behavior for this library and HHVM is the expected behavior.
