### ISSUE TITLE
Why do you use func_get_args?

### ISSUE THREAD

**Issue by sagikazarmark** [ramsey/array_column#5]
Why not simply checking the parameters?

**Comment by ramsey** [comment]
I wanted to provide functionality that behaves as closely to the native PHP function as possible, so I'm using `func_num_args()` and `func_get_args()` to test the arguments. The original function did not have defined parameters in the method signature. Those were added to make the code more readable.

I suppose now that the parameters are defined in the method signature I could just use the name of the parameter rather than `$params[0]` and so forth. However, I recall there being a specific reason I continued to use the `$params` array, but I can't recall what it was at this time. :-)

**Comment by sagikazarmark** [comment]
Ah, if you remember it, let me know. The reason I am asking is that I am backporting some hash_* functions and I remembered this backport of array_column, so I checked it's implementation and found this.
