### ISSUE TITLE
Recommended usage

### ISSUE THREAD

**Issue by sagikazarmark** [ramsey/array_column#8]
I am currently working a on a project which is used on multiple servers with multiple PHP versions.

Until now I used put backport packages (like this) into require-dev (for testing) and support section of composer.json.

However recently I found out that I could even require it in all cases which has two effects:

- it gets installed in case of every installation (every PHP version, this is not so good)
- I don't have to manually install it based on the deployment environment

A third option is to install it globally on older servers, but I don't like that either.

Does anybody have a good answer for this? What is the best practice?

**Comment by ramsey** [comment]
If you'll note here: https://github.com/ramsey/array_column/blob/master/src/array_column.php#L12

This library does a check to see if the `array_column()` function already exists, so it should be safe to include it on all your servers, as there will be no conflict. I've made every attempt to ensure it behaves exactly like the core PHP function.

Does this answer your question?

**Comment by sagikazarmark** [comment]
Thank you for your answer.

Actually I am aware of that check, this is why installing it on every PHP version is possible at all.

My concern is that installing a package for every PHP version to support an EOL version...does it really worth it?

I am curious about how people do it in practice. I mentioned a few arguments, maybe there are more which help me decide whether it worth to add a dependency by default or just suggest it and people still using PHP 5.3 should deal with the case.

**Comment by ramsey** [comment]
I understand your question now. :-)

It's a hard decision because, technically, you need to require it, otherwise parts of your application won't work or may error out. If you only suggest it, then you'll need to do checks in those parts of your application that use it so that they either gracefully degrade or they throw nice exception messages.

I would recommend requiring it for the current version of your application/library, especially since so many people are still running PHP 5.3 and 5.4. With the next major version bump of your application/library, then maybe you consider setting your application's minimum PHP version requirement to 5.5 or 5.6 (or 7.0, when it comes out).

I'll leave this comment open for now, in case others want to respond with their own recommendations.

**Comment by sagikazarmark** [comment]
Makes sense. This is not such a big library that it takes too much resources to download/store/load it.

Also, even if I take the number of uses into consideration (the majority is 5.5 now IMO) it is probably better to install it always instead of suggesting it. As you said, there are many points where the application can fail because of badly installed dependencies.

Thanks for your response.

I think this is an interesting (and unanswered) question in the community related to backport packages.
